# Generated by Django 4.2.8 on 2023-12-13 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
